DEEPSORT:
  REID_CKPT: "deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2  # 余弦距离的最小值
  MIN_CONFIDENCE: 0.3 # 最小目标检测置信度
  NMS_MAX_OVERLAP: 0.5 # 最大IOU阈值
  MAX_IOU_DISTANCE: 0.7  # 最大的IOU距离
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  
